Origen-SDK/origen

lib/origen/commands.rb, lib/origen/commands/fetch.rb, lib/origen/pins/pin.rb, lib/origen/revision_control/design_sync.rb, lib/origen/specs.rb, lib/origen/specs/exhibit.rb, lib/origen/tester/vector_generator.rb
Stephen,
Have included some changes to the Core and brought it up to speed with v2.5.0.pre129. Please let me know.
Thanks,
Priyavadan
=> include changes upto v2.5.0.pre129

lib/origen/specs.rb, lib/origen/specs/checkers.rb, lib/origen/specs/spec.rb, spec/specs_spec.rb
Some improvements to the Spec API:
* $dut.spec can now be used as an alias for $dut.specs when looking up specs.
* Made spec objects a little nicer to work with in the console and made the output more
consistent with other APIs like the Register API.
This update has removed the :verbose option that was supported by some APIs, its implementation
was a bit confusing.
* For now multiple specs are shown in the console as an array of names, and single specs
are shown as a table. A future enhancement can be made in the future to view multiple
specs in tabular form if required.
* Added a test to clarify how fuzzy spec finding works, but no changes have been made
at this time.
~~~text
> $dut.specs
> $dut.specs
[:soc\_io\_vdd, :soc\_pll\_vdd, :sysclk, :junction\_temperature, :tnikhov2]
> …
=> Sync to v2.5.0.pre134

config/rgen.policy, lib/origen.rb, lib/origen/chips.rb, lib/origen/chips/chip.rb, lib/origen/chips/design_entry.rb, lib/origen/chips/doc_entry.rb, lib/origen/chips/note.rb, lib/origen/specs.rb, lib/origen/specs/note.rb
Please ignore typo in the branch name. This release will sync v2.5.0.pre144
=> V2.5.0.pre144

lib/origen/specs/spec.rb
- Changes made to internal version to support the transition have been omiited.
=> Sync to Internal version v2.5.0.pre149

origen.gemspec
- Added support for Ruby running on x64 bit Windows OS in the conditional logic when the app is run from its own workspace
=> Added support for Ruby running on x64 bit Windows OS

lib/origen/specs.rb, lib/origen/specs/exhibit.rb, spec/specs_spec.rb
Find some instances where knowing the override information is needed for exhibits.  Added that to this code.
Improved Continuous Integration Environment for specs.rb.  This find several issues in specs.rb.  Coverage for specs.rb should be 90%+ now.
=> Improve exhibits.rb, fix issues in specs.rb, and expand the specs.rb self-test

lib/origen/pins/virtual_pin.rb, templates/web/guides/models/pins.md.erb
Removed restrictions on what users can enter for virtual pin attribute :type.
Added web documentation on virtual pin description and usage
=> Updates to Virtual pin model

Gemfile.lock, lib/origen/regression_manager.rb
- It will be updated periodically.
=> Enhancements to regression manager

Gemfile.lock, config/version.rb, doc/history, lib/origen/specs.rb, lib/origen/specs/version_history.rb, spec/specs_spec.rb, spec/version_history_spec.rb
Gotten further along with version history and seems that this is the right path.  going to pull and continue work on this.
=> Version History Work.

lib/origen/pins.rb, spec/pins_v3_spec.rb
Made change to add_pin_group so that pins can be both a pin_group and pins.
=> Fixes and tests for Issues #69. 

Gemfile, Gemfile.lock, approved/nvm_add_pin_clocks.atp, lib/origen/pins/pin.rb, lib/origen/pins/pin_clock.rb, pattern/j750/add_pin_clocks.rb, spec/pin_clocks_spec.rb, templates/web/guides/models/pins.md.erb
Enhance pin clock feature to handle cases where 50% duty cycle isn't best fit.
=> Pin.clock enhancement to handle non-50%-duty-cycle

lib/origen/core_ext/fixnum.rb, spec/fixnum_spec.rb
handy method when creating spreadsheets from arrays/hashes
=> Added in 'to_spreadsheet_column' method for Fixnum coreext

templates/web/guides/models/power.md.erb
https://github.com/Origen-SDK/origen/issues/148
=> updated power domains model guide and fixed ERB file name

lib/origen/core_ext/numeric.rb
=> added a few more numeric unit methods

lib/origen/core_ext/numeric.rb
myserver:origen $ origen i
origen(main):001:0> 3.2.Gbps
=> 3200000000.0
origen(main):002:0> 3.2.Mbps
=> 3200000.0
=> Added in bits per second numeric extensions

lib/origen/remote_manager.rb
This was a change I've had in my workspace for a while. Very simple change to just print the name of the requiring plugin for remotes. I added this to help debug a startup issue when I knew what the remote was and why it wasn't working (URL changed) but had no idea which plugin was actually including it to go fix it. For example, the output will now look like:
=> Added printing the name of the app/plugin that included the remote.

lib/origen/commands/web.rb
=> Fixed issue #227

lib/origen/model/exporter.rb, spec/import_and_export_spec.rb, vendor/lib/models/origen/export1.rb, vendor/lib/models/origen/export1/block1.rb
[issue #245](https://github.com/Origen-SDK/origen/pull/244)
~~~ruby
model.add_virtual_pin :relay1
model.add_virtual_pin :relay2, packages: { bga: {} }
~~~
=> Added virtual pins to model import and export

lib/origen/users/user.rb
This probably needs more work before merging, e.g. would like some kind of encryption as discussed in #97 
Opening the PR early though for easy diff and to document the functionality.
This provides an API to allow application's to reference the password for the current user and cache it to prevent the user being constantly pestered for it when the application makes repeated API calls to 3rd parties.
Here is an example of how it works:
~~~text
stephen@ywing:~/Code/github/origen$ origen i
origen(main):001:0> User.current.id
=> "stephen"
origen(main):002:0> User.current.password
Please enter your password:
=> "blah"
origen(main):003:0> User.current.password
=> "blah"
origen(main):004:0> exit
stephen@ywing:~/Code/github/origen$ origen i
origen(main):001:0> User.current.password
=> "blah" …
=> Added basic password method

lib/origen/global_methods.rb
=> Revert "Dynamic Testflow Comments"

templates/web/guides/program/v93k.md.erb
related to this [issue](https://github.com/Origen-SDK/origen/issues/251)
=> updated docs to mention test method 'test_name' parameter

templates/web/guides/pattern/common.md.erb
Adds some more info on the overlay styles, including a new one - handshake
=> Added info on overlay styles

lib/origen/site_config.rb, lib/origen/site_config/config.rb
- Removed dependency on gems
- Some minor clean up to remove direct reference to @configs (did it when trying to figure out a bug, thought I would just keep it as its cleaner)
=> Patch to site_config per archive branch updates

lib/origen/sub_blocks.rb, spec/sub_block_spec.rb, templates/web/guides/models/defining.md.erb
Added method sub_block_group to support defining an associated group of similar sub_blocks, permitting any uniqueness desired between them.
=> Sub block groups

lib/origen/application/deployer.rb
Minor fix to web server directory.
=> Updated create_web_server_dir method to account for app_dir structure.

lib/origen/generator/comparator.rb, lib/origen/generator/flow.rb, lib/origen/parameters.rb, lib/origen/parameters/set.rb, spec/parameters_spec.rb
- comparator fix enables relative paths
- flow change allows option to not reload target
- param change enhances fail msg
- param fix for false values
=> minor stuff from BAC

lib/origen/utility/csv_data.rb
Minor fix-- to let Origen file_handler help find the CSV file.
=> Update to CSV data extractor to permit finding file in either app or plugin

lib/origen/parameters/set.rb, spec/parameters_spec.rb
=> Fix for issue #352

lib/origen/utility/mailer.rb
=> Removed password information from logger DEBUG output.

lib/origen/sub_blocks.rb, spec/sub_block_spec.rb
Minor update to upgrade how sub_block_groups are managed-- so that only a single instance is generated of a sub block group.
=> Fix sub block groups

lib/origen/users/ldap.rb
* made ldap_encryption a site config variable
* added BASE_DN to the ldap service instance
=> updated ldap to work for AMD

lib/origen/pins/pin.rb, spec/pins_v3_spec.rb
Related to issue #415 
@ginty If you point me in the right direction i can try to add a spec test for the current behavior that got broken.
=> reverted automatically setting pin type

lib/origen/application/configuration.rb
=> users can now optionally override the diff and copy commands
