Origen-SDK/origen

lib/origen/specs.rb
lib/origen/specs/exhibit.rb
spec/specs_spec.rb

There is a bug with Hash.filter where if the Hash is NilClass, then the filter will fail.  Changing to filter_hash allows for this corner case to be corrected.

Change Hash.filter to filter_hash(Hash, filter_criteria)

---

lib/origen/specs.rb
spec/specs_spec.rb

There is an issue if the global variable (e.g. @_notes, @_doc_resources, ..) is nil.  Currently, the tool will respond with a Fail that "Hash argument is not a Hash".  This has been changed so that the script looks to see if the variable is nil or empty before doing filter_hash.

Fix issue if a global variable is nil.

---

lib/origen/specs.rb
lib/origen/specs/documentation.rb
spec/specs_spec.rb

This class allows for documentation to control how the map output and the topic output would look.  This is just the base class and individual companies and people can add on to make it specific to their strategy.

New Class for Specs Documentation

---

lib/origen/regression_manager.rb

- when workflow is git (i.e: echo latest | origen regression... will check against latest and not require user input)
- this should help with regressions using continous integration systems

added capability to support automated regression testing

---

Gemfile.lock
lib/origen/specs/override.rb
lib/origen/specs/spec.rb

There is a use case where a spec might be disabled/removed due to voltage or other considerations.  This allows the override to hide that spec for a particular deriative of a SoC.

Add the ability to have a spec hidden based off of the License Plate

---

Gemfile.lock
lib/origen/specs.rb
spec/specs_spec.rb

Added capability to the 'show_specs' method to allow the user to find all the specs wth a given spec symbol, rather than by spec name.

Added capability to find specs using :symbol attribute

---

Gemfile.lock
lib/origen/specs.rb
lib/origen/specs/checkers.rb
lib/origen/specs/documentation.rb
spec/specs_spec.rb

Added Nokogiri::XML::NodeSet as a class to ignore when evaluating limits.

Remove limit checker on Nokogiri::XML::NodeSet

---

Gemfile.lock
lib/origen/regression_manager.rb

- added capability to provide the reference workspace path and version number.
- fixed minor bug while setting up the origen workspace. For some reason, bundle install is also needed along with origen -v in a newly built workspace.

Minor update to regression manager

---

lib/origen/log.rb
spec/log_spec.rb

In an application, I need to be able to parse the log messages being sent.  At the end of my app, I need to go through and categorize Error, Warning, and Success messages depending on where they occur.
For example, if I am importing something and it passes, I want to be able to write:
`
Origen.log.success('Block A', :import)
`
If it fails, I want to write:
`
Origen.log.error('Block B', :import)
`
At the end of my app, I want to output the errors depending on the section.
~~~~
Origen.log.msg_hash[:error].each do |section, arr|
arr.each do |a|
p "#{section.to_s.upcase}::: #{a}"
end
end
~~~~

Store Log Messages into a Hash for debug purposes

---

lib/origen/pins.rb
lib/origen/pins/other_pin.rb
lib/origen/pins/pin_bank.rb
lib/origen/pins/pin_collection.rb
spec/pins_v3_spec.rb

In prepping for a new project, I needed the ability to handle Other Pins.  Other pins include the following types:
*  No-Connects
*  Reserved
*  DePopulated Pins
Used Virtual Pin as a base for the Other Pins and copied its spec tests to ensure that the code works as expected.

Add Other Pins to Pin Group

---

lib/origen/registers/bit_collection.rb

Example 'read_register' code making use of new :sync flag to log OrigenLink pattern execution in a readable format:
```
def read_register(reg, options = {})
arm_debug.ahbap.read_register(reg, options)          
if options[:sync] != true and reg.respond_to?('data') and tester.link?
link_log(reg, :read)
end
end
def link_log(reg, operation, options = {})  
if operation == :read
expected = reg.data
reg.sync!
printf "Read reg:  %-20s Address: 0x%s %30s\n", reg.name.to_s, reg.address.to_s(16).rjust(8, '0'), "Read Data:  0x" + reg.data.to_s(16).rjust(8, '0')
if expected != reg.data
printf "%s %29s\n\n", "----------------------  FAIL  ----------------------".red, "Expected:   0x" + expected.to_s(16).rjust(8, '0')
end
else
printf "Write reg: %-20s Address: 0x%s %30s\n", reg.name.to_s, …
```

Added indication sync is being run to allow register action logging.

---

lib/origen/pins.rb

When running tests, there was an issue when pins is empty.  When pins is empty, group will always be nil.  With fix, it will check to see if group is nil, if nil, then check to find the expected group.

Issue seen in add_pin_group when pins is empty.

---

lib/origen/pins/pin.rb
lib/origen/pins/power_pin.rb
spec/pins_v3_spec.rb
templates/web/guides/models/pins.md.erb

@welguisz could you give this a review pls?
It gives every pin a default meta data hash:
~~~ruby
add_pin :pinx
pins(:pinx).meta   # => {}
~~~
And allows it to be overridden by function:
~~~ruby
add_pin :pin2, meta: { vol: 0.4, voh: 0.6 }   # Define default meta data
pin(:pin2).add_function :tdo
pin(:pin2).add_function :nvm_done, meta: { voh: 0.7 }  # Override some of the meta data
pin(:tdo).meta         # => { vol: 0.4, voh: 0.6 }
pin(:nvm_done).meta    # => { vol: 0.4, voh: 0.7 }
~~~
The above merging of default and function-specific hashes will actually be done for any FUNCTION_SCOPED_ATTRIBUTE which is defined as a Hash.
However if the attribute is not a Hash then it will skip the merging, so it should play nice with any legacy apps where the meta data is not assigned to a hash, see …

Added better pin meta data API and some power pin attributes

---

templates/web/guides/pattern/common.md.erb

Not sure how, but this commit didn't get included in PR #75.  Simple documentation update.

Add mention and link about pin clock setup in the Pattern Generation Section

---

lib/origen/remote_manager.rb

Fixed issue with the remotes manager on Windows that was causing
Origen to infinitely populate the remotes, never allowing Origen to actually
startup.
The issue's source was using Unix commands, whose results were slightly different
between Linux and Windows, causing the .current_version data to be slightly different
than expected. The use of quotation varied slightly as in the example below:
The extra quotations on Wiindows are throwing off the remote manager. The manager would keep trying to compare, for example, 0.1.1 with "0.1.1" and never getting the "correct" version, causing it to spin infinitely as it repeatedly populates the remotes.
The solution was to just use a straight Ruby approach to write the .current_version file instead of Unix commands. Ruby's results are stable across …

Remotes Manager Fix For Windows

---

lib/origen/registers.rb

Initialized @max_address_reg_size to prevent nil case for single-register sub-block.

Bug fix - @max_address_reg_size with single-reg sub-block

---

bin/origen
lib/origen/commands/new.rb
origen_site_config.yml

This PR adds a new site config parameter to allow a company to add their own application starter templates.
The Origen app generators plugin will in due course be enhanced to provide an option of creating a new plugin that should be used to contain company-specific app templates/generators.
This update provides the Origen core hooks necessary for the 'origen new' command to be able to pick up such generators, either from an internal gem server, a file location, or from a Git repo.
A user's local copy of the generators will be refreshed every 24 hours or anytime they supply a --fetch option to 'origen new'. This ensures that they will always be pointing to the latest and greatest templates.
The ability to specify a previous version of the generators has been removed. It may be …

App generators

---

templates/web/guides/compiler/subtemplates.md.erb

I thought this might help people avoid passing options[:file] to the sub-template like I did :)  I changed my options key from :file to :csv_file and everything worked fine.

updated compiler subtemplates web template

---

lib/c99/nvm.rb
lib/origen/registers.rb
lib/origen/registers/bit_collection.rb
spec/container_spec.rb
spec/features_spec.rb
spec/parameters_spec.rb
spec/reg_spec.rb
spec/site_config_spec.rb
spec/spec_helper.rb
templates/web/guides/models/registers.md.erb

Convenience of being able to grab all registers of a model that match a given regular expression.
Example: set configuration register for all ADCs (i.e. adc0_cfg, adc1_cfg, etc.) 
dut.regs('/adc\d_cfg/').each do |k,v|
v.write!(0x000A_5000)
end

Add regex as possible input to regs() method

---

config/application.rb
lib/origen.rb
lib/origen/application.rb
lib/origen/remote_manager.rb
lib/origen/revision_control/git.rb
templates/web/guides/misc/remotes.md.erb

This PR adds the ability to mark remotes for development use only, so that they will only be populated when developing a plugin and not when that plugin is used by a top-level app.
It also adds a patch to make `Origen.app.rc` return nil instead of crashing in the corner case where config.rc_url has been defined but the application has not been initially checked in yet.

Private remotes

---

lib/origen/parameters/set.rb
spec/parameters_spec.rb

~~~ruby
[1] pry(#<RSpec::ExampleGroups::Parameters>)> $dut.params
=> {:tprog=>20,
:erase=>{:time=>4, :pulses=>5},
:test=>{:ac=>{:period=>1.0e-08}, :func=>#<Proc:0x002b0475292940@/users/bcaqueli/origen/origen/spec/parameters_spec.rb:16 (lambda)>},
:vdd=>{:nom=>1, :min=>0.8, :max=>1.2}}
[2] pry(#<RSpec::ExampleGroups::Parameters>)> $dut.params.to_flat_hash.include?('erase.time')
=> true
[3] pry(#<RSpec::ExampleGroups::Parameters>)> $dut.params.to_flat_hash['test.ac.period']
=> 1.0e-08
[4] pry(#<RSpec::ExampleGroups::Parameters>)> $dut.params.to_flat_hash(delimiter: '_').include?('erase_time')
=> true
[5] pry(#<RSpec::ExampleGroups::Parameters>)> $dut.params.to_flat_hash(delimiter: '_')['test_ac_period']
=> 1.0e-08
~~~

Added in 'to_flat_hash' method for Parameter::Set class

---

lib/origen/commands/compile.rb
lib/origen/commands/generate.rb
lib/origen/commands/helpers.rb
lib/origen/commands/interactive.rb
lib/origen/commands/lint.rb
lib/origen/commands/lsf.rb
lib/origen/commands/program.rb
lib/origen/commands/rc.rb
lib/origen/commands/save.rb
lib/origen/commands/time.rb
lib/origen/commands/web.rb
lib/origen/core_ext/array.rb
lib/origen/generator/job.rb
lib/origen/generator/pattern.rb
templates/web/guides/misc/commandsov.md.erb

Allow applications (or plugins) to specify an 'option name' for command option extensions which, when set, will register in the Origen Core option parser.
Example:
This example shows how origen_testers can extend the 'generate' command with a '--compile' option which, when set, will register in the Origen Core option parser as *testers_compile_pat: true*.  In turn, that can be passed along to various processes associated with the base command (e.g. can be passed to the listener pattern_generated for post-pattern pattern compilation).
origen_testers: config/shared_commands.rb
```ruby
case @command
when "generate"
@application_options << ['--compile', 'Compile the current pattern or the list', { option: 'testers_compile_pat' }]
```

Pipeline from application command extensions to origen core option parser

---

templates/web/guides/pattern/common.md.erb

Web guide update to explain how to use tester implemented overlay/capture features added in origen_testers 0.10.0

Update pattern generation common api with overlay/capture information

---

lib/origen/power_domains/power_domains_collection.rb

The original printer portion of the inspect function assumes that all of the power domains have the same list of attributes to print out.  If any one of the attributes are missing, you could get glitches in the output.  This PR corrects that.  I've also added back in the voltage range attribute which was incorrectly excluded.
Here's an example of the original output were two of the domains are missing the setpoint attribute.
Here's the corrected output

Fixed power_domain inspect output for some cases

---

lib/origen/regression_manager.rb

I couldn't get the regression manager to work in one of my apps, I suspect probably related to some relatively recent changes to the Origen boot process.
Anyway, these changes fixed it.
It's basically removing the regression manger's use of `bundle exec` when launching origen commands whenever Origen is in charge of bundler (should be the case in 99-100% of apps).
Not sure why it used `bundle exec` originally, but the way it is now aligns to how you would invoke origen directly from the command line.

Fix regression manager's use of bundle exec

---

lib/origen/registers.rb
lib/origen/registers/bit_collection.rb
spec/reg_spec.rb

This pull request intends to add a method to provide for better coding style when dealing with large numbers of bit manipulations within a register.  These manipulations can be hard to read, and error prone when '!' is in play.
Previous code style:
```
$dut.mtr.mct.reg(:bstart).bits(:bstart).write(0x4) # Program BIST but don't start them
$dut.mtr.mct.reg(:bstart).bits(:cens).write(1) 
$dut.mtr.mct.reg(:bstart).bits(:cenac).write(1)
$dut.mtr.mct.reg(:bstart).bits(:brst).write(1)
$dut.mtr.mct.reg(:bstart).bits(:cof).write(1)
$dut.mtr.mct.reg(:bstart).bits(:clken).write(1)
$dut.mtr.mct.reg(:bstart).write!
```
New coding style:
```
$dut.wreg($dut.mtr.mct.reg(:bstart)) do |r|
r.bits(:cens).write(1) 
r.bits(:cenac).write(1)
r.bits(:brst).write(1)
r.bits(:cof).write(1)
r.bits(:clken).write(1) …
```

Add block write!/read! ability to allow for better coding style for bit manipulations.

---

lib/origen/pins/pin.rb
lib/origen/power_domains/power_domain.rb
spec/pins_v3_spec.rb
templates/web/guides/models/pins.md.erb

~~~ruby
it 'add DIB metadata based on package scope' do
$dut.add_package :pcs
$dut.add_package :bga
$dut.add_pin :tdo, packages: { bga: { location: 'BF32', dib_assignment: [10104] }, pcs: { location: 'BF30', dib_assignment: [31808] } }
$dut.pins(:tdo).add_dib_meta :pcs, { :net_name=>"/DUT_TDO_TC", :connection=>"PE118.16", :slot=>"PE118", :spring_pin=>"16" }
$dut.pins(:tdo).add_dib_meta :bga, { :x=>2000.0, :y=>-15600.0, :net_name=>"TDO", :connection=>"PE117.08", :slot=>"PE117", :spring_pin=>"08" }
$dut.package = nil
$dut.pins(:tdo).dib_meta.should == {}
$dut.package = :bga
$dut.pins(:tdo).dib_meta.should == {:net_name=>"TDO", :connection=>"PE117.08", :slot=>"PE117", :spring_pin=>"08" }
$dut.package = :pcs
$dut.pins(:tdo).dib_meta.should == { :net_name=>"R92/DUT_TDO_TC", …

Added in package scoped DIB metadata to Origen::Pins::Pin

---

lib/origen/generator/compiler.rb

files such as 'shell.lev.dpspins.erb' would fail before.

Fixed compiler bug if template files contained multiple '.'

---

lib/origen/application.rb
lib/origen/callbacks.rb
spec/sub_block_spec.rb
templates/web/guides/misc/callbacks.md.erb

The previous implementation of sub_blocks instantiated the objects straight away, which meant that they were always listening for callbacks after the target was loaded.
Since sub_blocks are now lazy-loaded this is no longer the case. 
I think the new approach is vastly preferable, however there is not really any way to have the best of both worlds where they are instantiated only when required but are also actively listening for callbacks before then.
I've added some documentation to make the new behavior clearer and I don't think this should really be a problem for applications to deal with.
I have added one exception case for the `on_create` callback, since this is intended to be used as a replacement for `initialize` which can be used to init a model with the guarantee that the target …

Fix for #186

---

lib/origen/model_initializer.rb
spec/sub_block_spec.rb

This is a further patch for #186 
Controllers are not explicitly registered as callback listeners, but they do work like one since their responsible model listens and that will proxy any requests for callback methods that are implemented by the controller.
The previous update for #186 means that any model which implemented on_create will have that called when it is instantiated, but it did not account for the fact that a controller could have one too.
This update adds the same on_create exception for controllers.

More fixes for #186

---

lib/origen.rb
lib/origen/application.rb
lib/origen/application/runner.rb
lib/origen/commands/version.rb
lib/origen/commands_global.rb
lib/origen/global_app.rb
lib/origen/log.rb

Historically, Origen has been in a very feature limited mode when running outside of an application workspace, where it has only really provided the ability to create a new application.
With the addition of [global plugin commands](http://origen-sdk.org/origen/guides/plugins/creating/#Sharing_Global_Commands), and the concept of [centrally maintained Origen plugin bundles](http://origen-sdk.org/origen/guides/advanced/invocations/#Site_Config_For_Toolset_Installations), it is going to be more common to see plugins provide functionality that can be invoked anywhere and which might not depend on the concept of a current application.
However, many of Origen's core functionality expects an application to be present, whether it is really needed or not, and many things don't work when they are …

Added global app instance when running outside an app

---

bin/origen

When a user install is in play, a Gem bundle gets created in the location pointed to by `site_config.user_install_dir`.
This creates an `origen` executable at `#{site_config.user_install_dir}/lbin/origen` and when Origen is invoked through that it will execute under the context of the gem bundle defined by `#{site_config.user_install_dir}/Gemfile`.
Normally, users of Origen don't need to worry about that too much, since we recommend that they add `./lbin` to their path, so when they type `origen` at the command line it is invoked in the context of their app's gem bundle.
Even if they happen to invoke some other `origen` executable, the bin script contains some logic to automagically re-launch Origen under the correct bundle environment.
Such code does not exist in the bin script branch …

Fix for #192 (Constant bundle install when invoking under user Origen env)

---

lib/origen.rb
lib/origen/commands.rb
lib/origen/commands_global.rb

No longer grimace at mis-aligned command summaries:
~~~
[nxa21353@acv0145 origen]$ origen
Usage: origen COMMAND [ARGS]
The core origen commands are:
environment        Display or set the environment (short-cut alias: "e")
target             Display or set the target (short-cut alias: "t")
mode               Display or set the mode (short-cut alias: "m")
plugin             Display or set the plugin (short-cut alias: "pl")
generate           Generate a test pattern (short-cut alias: "g")
program            Generate a test program (short-cut alias: "p")
interactive        Start an interactive Origen console (short-cut alias: "i")
compile            Compile a template file or directory (short-cut alias: "c")
exec               Execute any Ruby file with access to your app environment
rc …

Relief for your OCD

---

lib/origen/application/deployer.rb

This fixes a run time error when running 'origen web compile -r'.  The 'DO NOT HAND MODIFY' directory that gets created previously had a ':' in the name which fails to get created on Windows.

Windows doesn't all directory names with ':'

---

lib/origen/commands_global.rb
lib/origen/site_config.rb
origen_site_config.yml
spec/site_config_spec.rb
spec/spec_helper.rb
templates/web/guides/advanced/invocations.md.erb
templates/web/guides/plugins/creating.md.erb
templates/web/guides/starting/company.md.erb
templates/web/guides/starting/gems.md.erb
templates/web/guides/starting/invoking.md.erb
templates/web/guides/starting/workspace.md.erb

The TL;DR of this: Origen can now register plugins installed at the system level and can run global commands defined there. Also, this includes the enhancements for issue #183 and some methods to dynamically mess with the site config.
Hi,
This is a PR to add a requested feature which allows for global commands to be run when gems are installed at the system level.
Previously, in order to run global commands, you had to setup a TR or user install. TR users could reference a TR install, but that still required some sort of setup (usually a shell script to setup environment variables). With this PR, gems installed at the system level (using gem install), will be registered as Origen plugins, and are capable of adding global commands.
For example, to run a global command in the gem …

Express global commands

---

lib/origen.rb
lib/origen/org_file.rb
lib/origen/org_file/interceptable.rb
lib/origen/org_file/interceptor.rb
lib/origen/pins/function_proxy.rb
lib/origen/pins/pin.rb
lib/origen/pins/pin_collection.rb
lib/origen/value/bin_str_val.rb
lib/origen/value/hex_str_val.rb
spec/value_spec.rb

This adds the ability to generate org files (Origen vector file format) as described in this RFC: https://github.com/Origen-SDK/rfcs/pull/7
This is not intended to be a user-facing feature, but is internal architecture for use within Origen and its plugins to generate org files or to otherwise capture and process sequences of operations.
~~~ruby
Origen::OrgFile.open("some_id") do |org_file|
end
org_file = Origen::OrgFile.open("some_id")
org_file.close
~~~
By default, the Org file will be created at `#{Origen.root}/pattern/org/#{current_target}/#{id}.org`, though the `open` method will accept `:path` and `:filename` options is you want to change it.
The only API the org_file object itself really provides to the application space is to check whether or not the underlying file exists: …

Org file infrastructure

---

lib/origen/site_config.rb

@ginty was able to update our system gems to use Origen post express-global-commands. The main feature worked but there was one bug and one inconsistency (I wouldn't call it a bug based on what I meant to do, but was convinced that what I meant to do was wrong... so okay, two bugs).
Firstly, the user's site config was being ignored. Since the home_dir is now being evaluated during the site config parsing, the user_install_dir was actually pointing to nil the first time around. So, even if you had a user site config, it wouldn't be added. Updated the site config to first parse all the site configs in the normal sense, then jump to <code>home_dir</code> and throw in that site config, if it exist. This should get user installs going again. This still takes place before any gems are installed …

Express global commands bugfix

---

lib/origen/parameters.rb
spec/parameters_spec.rb
templates/web/guides/models/parameters.md.erb

Example:
`# Default block bin to 12 or let top-level parameter override if specified`
`my_block_bin = dut.param?('test_program.hard_bin.my_block') || 12`
I will add documentation and spec tests if you think the syntax looks ok.

New param method 'param?' to quickly test for existence and return value

---

lib/origen/model.rb
spec/model_spec.rb
templates/web/guides/misc/callbacks.md.erb

First discussed [here](https://stackoverflow.com/questions/48811004/changing-object-data-using-with-mode-method).
~~~ruby
class MyModel
include Origen::Model
attr_reader :my_version
attr_accessor :mode_changed_count
def initialize
@my_version = version
add_mode :mode1
@mode_changed_count = 0
end
def on_mode_changed(options)
@mode_changed_count += 1
end
end
it 'on_mode_changed callback works' do
m = MyModel.new
m.modes.should == [:mode1]
m.mode.should == nil
m.mode_changed_count.should == 0
m.mode = :mode1
m.mode_changed_count.should == 1
end
~~~

on_mode_changed callback added

---

Gemfile.lock
lib/origen/revision_control/perforce.rb
origen.gemspec

The p4ruby gem has caused a bit of havoc within the NXP environment due to it requiring a native extension which it seems to want to download from a 3rd party location via FTP.
We could probably update our firewall rules or whatever to fix this, but it generally highlights that its not worth including non-native Ruby gems if they don't add significant value to a majority of users.
For this reason, the Perforce driver has been extracted to a plugin, making the p4ruby dependency opt-in rather than included by default.
All this means is that any applications that want to use the Perforce driver capability must now add this to their Gemfile:
~~~ruby
gem 'origen_perforce'
~~~
After that, it is business as usual.

Remove dependency on p4ruby gem

---

lib/origen/global_methods.rb

Hijack cc method when called during program generation for creating dynamic descriptions, requires corresponding origen_testers change.

Dynamic Testflow Comments

---

Gemfile.lock
lib/origen/commands.rb

this allows code in `boot.rb` to query `Origen.current_command`, relating to [this discussion](https://stackoverflow.com/questions/49636962/can-origen-current-command-be-nil).

changed when Origen.current_command is available

---

lib/origen/model.rb
templates/web/guides/misc/callbacks.md.erb

Pass self into on_mode_changed so that listeners can self-identify (and then optionally perform some task).  Mainly used when sub-models (e.g. sub-blocks) contain modes that are separate from any top-level modes (or modes of other sub-models).

Allow self-identification in on_mode_changed callback

---

lib/origen.rb
lib/origen/version_string.rb
spec/version_spec.rb

I just found a bug in OrigenSim because I expected this to work:
~~~ruby
Origen::VersionString.new('0.10.0') < '0.8.8'
~~~
Now it does, and so do all other regular comparison operators.
The original API is still supported for masochists, but the specs have been re-written to be examples of using the improved alias methods.

Make regular comparison operators work

---

lib/origen/pins/pin.rb
lib/origen/pins/pin_collection.rb
pattern/j750/j750_workout.rb

Registers are operated on using read/write.  It's common for people to attempt to use read/write with pins as well, which leads to run time errors and a search for the proper method name.  Seems intuitive to have these alias methods instead.

Add read/write alias methods to pin/pin collection

---

lib/origen/registers.rb
lib/origen/registers/reg.rb

Any bit name that matched a reg_level_attribute ('feature', **'reset'**, 'memory', etc.) was being clobbered during register creation (using add_reg or reg do block).  Patch that adds a underscore prefix to the attributes in the class hash and handles ignoring it when creating the instance variable associated with those attributes.

Allow bit names that are similar to 'reg level attributes'

---

lib/origen/registers.rb
lib/origen/registers/reg.rb
spec/reg_spec.rb

PR #271 attempted to handle bit names that matched any of the REG_ATTRIBUTE keys by adding an underscore to the REG_ATTRIBUTES key strings and then remove the underscore when creating the instance_variables during initialization.  This PR adds an additional key:val in the bit_info hash created in the  reg Placeholder, so that the reg.initialize can correctly determine when to remove a non-underscored attribute.

Patch PR #271 implementation

---

lib/origen/core_ext/numeric.rb
pattern/j750/timing.rb

Added helpers to create pattern wait durations like this:
~~~ruby
10.ms!    # Shorthand for tester.wait(time_in_ms: 10)
~~~
The driver for adding this is to make it quick and easy to advance time while in an OrigenSim interactive session.

Added numeric wait helpers

---

bin/origen

Bootsnap cache is not reliable when running remotely and doesn't really make sense to rebuild it for a one-time run, so just go ahead and disable bootsnap for LSF jobs.

Do not use Bootsnap for LSF remote execution

---

lib/origen/pins.rb
spec/pins_v3_spec.rb
templates/web/guides/models/pins.md.erb

I didn't see any existing option to model pin groups whose indexes don't start at 0, so added an <code>:offset</code> option to <code>#add_pins</code> for this.
This was actually noticed from using OrigenSim where my <code>origen.v</code> file wasn't correctly mapping <code>ptc[19:1]</code> and I was having to manually adjust all the pin drivers. Nothing a find & replace couldn't fix, but still seemed like something to fix upstream. Traced this back to <code>#add_pins</code> not having an option for an offset.
In general, we don't see this very much here and up until the introduction of OrigenSim I never added entire pin groups before anyway, so this just surfaced.
If this is accepted, I'll update OrigenVerilog to pass this option to <code>#add_pins</code>.

Pin group offsets

---

bin/origen
origen_site_config.yml

A small update to add the ability to output broadcast messages (shown to all users every time they invoke Origen) from site configs.
The given text it just output verbatim to the console and can be optionally colored, the example output is shown below.
The intended use case within NXP is to allow us to deprecate Origen/Ruby installations and advise users to transition to a supported installation.
~~~text
stephen@xwing:~/Code/github/origen$ origen -v
These lines will be output to the console in regular text
These lines will be output to the console in amber text
These lines will be output to the console in red text
These lines will be output to the console in green text
Application: 0.38.0
Origen: 0.38.0
~~~

Added site config broadcast system

---

lib/origen/model/exporter.rb
spec/import_and_export_spec.rb

update exporter to skip nil attributes of sub_blocks

---

lib/origen/revision_control/git.rb

This PR is an attempt to make the .can_checkin? method more robust. It was incorrectly returning false on an 'origen web compile -r' operation. There were no local changes at the time. So, the push dry run failed. The expectation is that updating the push dry run to attempt creating a remote branch will prevent this type of false fail.

make git.can_checkin? robust

---

lib/origen/model/exporter.rb
spec/import_and_export_spec.rb

- Changed exported directory path to sub_block class files to use <code>"#{Origen.root!}/"</code> (relative paths)
- Added an export option <code>:rm_rb_only</code> to leave behind non-ruby code (ie revision control metadata) for cases where an existing model is being updated
@williamcheong I think this will resolve your issues with exporter

Exporter updates

---

lib/origen.rb
lib/origen/registers/bit.rb
lib/origen/registers/bit_collection.rb
lib/origen/value/bin_str_val.rb
lib/origen/value/hex_str_val.rb
spec/reg_spec.rb
spec/value_spec.rb

Contains the following fairly minor updates to support the latest version of OrigenSim:
- Adds an `unknown` attribute to bit objects that can also be set on a bit collection via `my_bit_collection.unknown = true`.
- This is not really intended for user space usage and it is to provide a way for OrigenSim to track when an X or Z has been read back from a simulation
- The `BitCollection#status_str` method has been updated to return `?` for the value of such bits
- Improved the error message when creating a hex or bin string value that contains illegal characters and gave each case a dedicated error to give OrigenSim or other higher level code the possibility of handling such errors in future.
-  Took the opportunity to clean up by removing the status code attribute from Origen errors. This …

Minor updates for OrigenSim

---

lib/origen/sub_blocks.rb

Pretty minor fix to reconstruct the full path after splitting the caller on ':'
@ginty are there other places where a similar operation is done?

Patch for path on windows

---

lib/origen/application.rb
lib/origen/loader.rb

Fix for an intermittent bug which we believe is caused by the paths in the `@blocks_files` being partially garbage collected in error.
This change stores the paths as strings rather than `Pathname` objects and hopefully the simpler object storage circumvents whatever the root cause is.
It seems to in repeated loop testing, I have not been able to invoke the problem with this change after running continuously for a few hours.

Fix for GC bug

---

lib/origen/model/exporter.rb

Includes the pin type attribute in exported models.
This enables the pins file generated by the `origen sim:build` to identify WREAL pins as analog type.

Include pin type in exported models

---

lib/origen.rb
lib/origen/sub_blocks.rb

There are several places in the core and origen_testers (likely other plugins as well) where the file path + name and/or number are extracted from the caller by splitting on ':'. On windows the file path includes a ':' after the drive letter. Most of the instances of this that I found have been patched by recombining the first 2 array elements after the split if running on Windows.
This PR is to add a centralized splitter utility rather than either duplicating the patch repeatedly.
Here is an existing example of the bug
https://github.com/Origen-SDK/origen_testers/blob/bbff2a296eaffbdcf696e16fb09f91444de80a4e/lib/origen_testers/flow.rb#L169-L173
When running from Windows, called_from[1] will be the file path and name excluding the drive letter.
The fix would be
~~~ruby
called_from = …

Caller info splitter utility

---

config/application.rb
helpers/url.rb
lib/origen/commands/new.rb
lib/origen/users/user.rb
lib/origen/utility/collector.rb
origen.gemspec
templates/nanoc/layouts/bootstrap.html.erb
templates/shared/web/_logo.html
templates/web/404.html.erb
templates/web/guides/advanced/newapps.md.erb
templates/web/guides/controllers/shadow.md.erb
templates/web/guides/installation/installwin.md.erb
templates/web/guides/models/power.md.erb
templates/web/guides/models/registers.md.erb
templates/web/guides/models/specs.md.erb
templates/web/guides/plugins/creating.md.erb
templates/web/guides/plugins/importing.md.erb
templates/web/index.html.erb
templates/web/layouts/_cyborg.html.erb
templates/web/partials/_navbar.html.erb
templates/web/plugins.md.erb
templates/web/tour/basics.html.erb
templates/web/tour/design-engineering.html.erb
templates/web/tour/test-engineering.html.erb
templates/web/videos/2-model-data-import.md.erb
templates/web/videos/6-create-program-tests.md.erb

I haven't yet done an update for the `index.html` symlink.
Looking in the code it seems it already has code to generate a symlink for `index.html' pointing to `latest/index.html`, however it is only created if `index.html`.  
[https://github.com/Origen-SDK/origen/blob/master/lib/origen/application/deployer.rb#L155](https://github.com/Origen-SDK/origen/blob/master/lib/origen/application/deployer.rb#L155)
I think we need to update this also to delete the toplevel `index.html` if there and implement the symlink.  This should work even if symlink already there.
Thoughts?

Updated web links to origen-sdk.org to use HTTPS protocol due to website

---

lib/origen/users/user.rb
spec/user_spec.rb
templates/web/guides/starting/commit.md.erb

fixes #353 
I also added some code that checks if a different user_id is defined in the site config in the user directory. Running into issues where the Linux Subsystem in windows 10 uses a different user id than the corporate ID. If there is another way to change this, I am open to discussing.

fixes #353

---

approved/nvm_concurrent.atp
lib/origen/generator/pattern_sequence.rb

Sourceless pattern generation was broken when running `origen g` with the `--seq` option to generate a (concurrent) sequence, this fixes it.

Fix sourceless pattern generation for sequences

---

lib/origen/file_handler.rb

Added option to `clean_path_sub_program` in `file_handler.rb` to support the option of importing a sub-flow NOT pre-pended with underscore.

Updated clean_path_to_sub_program to support no-underscore filename

---

lib/origen/application/configuration.rb
lib/origen/application/plugins.rb
lib/origen/application/release.rb
lib/origen/utility.rb
lib/origen/version_string.rb

The change in the plugins file was a workaround so I could test out the PR.  **Question:** Would we ever allow someone to make a release where the session mode is set to 'debug'?

Adding support for 'origen rc tag' without prepending 'v' to the tag

---

lib/origen/sub_blocks.rb

When sub-blocks are loaded by the autoloader, some errors (those related to missing references) in the sub-block files can be swallowed and in-correctly reported to the user "as unable to find (sub-block) class X".
Such cases were very hard to debug for the user!
This fixes it by being more selective about what is considered a maskable error and it now correctly reports the underlying error in such cases.

Report syntax errors within sub_block classes properly

---

lib/origen/commands/archive.rb

This fixes a bug in the archive command where any directory within the application matching one of the exclude dir names is excluded, whereas the intention was for only directories matching the exact path to be excluded.
e.g. currently any dir named 'dist' anywhere in the app will be excluded, but now only `#{Origen.root}/dist` will be excluded.

origen archive command bugfix

---

lib/origen/application/lsf_manager.rb
templates/web/guides/runtime/global.md.erb

Added new site config variable so that the sourcing of the setup file gets skipped.
The source_setup is needed for the 'older' RGen installations (which no one should be currently using anyways)

Added new site config variable 

---

lib/origen/core_ext/numeric.rb
spec/numeric_spec.rb

This is to handle negative as_units inputs the same as positive inputs. If we do not compare absolute value, we will fall through to the else block for all negatives.
Current:
irb(main):001:0> 10.as_units('[mA]')
=> "10[mA]"
irb(main):002:0> -10.as_units('[mA]')
=> "-1.000e+01[mA]"
irb(main):003:0>
Desired:
irb(main):001:0> 10.as_units('[mA]')
=> "10[mA]"
irb(main):002:0> -10.as_units('[mA]')
=> "-10[mA]"

Add absolute value checks to as_units for negative inputs

---

.travis.yml
config/rubocop/strict_enabled.yml

With this enabled, there's a scenario where its impossible to get lint to pass, for example in a v93k flow with a multiline proc in the on_fail option:
``` ruby
func :my_test, on_fail: -> do
end
```
results in
`Style/Lambda: Use the lambda method for multi-line lambdas.`
So, moving to lambda style:
``` ruby
func :my_test, on_fail: lambda do
end
```
throws up a stack trace when I run origen program:
```
COMPLETE CALL STACK
-------------------
tried to create Proc object without a block
```
Found out that to get that to work, I have to use braces {}:
``` ruby
func :my_test, on_fail: lambda {
}
```
Which now generates correctly with origen p, but now I'm back to a lint fail:
`Style/BlockDelimiters: Avoid using {...} for multi-line blocks.`

disable lambda style to prevent lint block

---

spec/format/origen_formatter.rb
spec/spec_helper.rb

When using rspec 3.x, a failing spec test would result in a stack trace rather than rspecs helpful summary output of failures.
Now support for rspec3, while maintaining < rspec 3 versions

rspec 3 formatter support

---

spec/format/origen_formatter.rb

I ran into this with rspec version 3.9 and I ran `bundle exec rspec spec/myspec.rb`.  It gives this error:
~~~shell
An error occurred while loading ./spec/pin_groups_spec.rb.
Failure/Error: require "#{Origen.top}/spec/format/origen_formatter"
NameError:
uninitialized constant RSpec::Version
~~~

fix for when rspec is on latest version 3.9 and you run bundle exec rspec

---

lib/origen/site_config.rb

I tried setting up an ORIGEN_CENTRALIZED_SITE_CONFIG environment variable and ran into some issues.
When I point my app to a clone of the origen repo, I find 2 site configs as origen expects:
```
0: /.../origen/origen_site_config.yml (local)
1: /.../origen/origen_site_config.yml.erb (local)
```
When I just use a gem dependency however, I just find 1:
```
0: /.../.origen/gems/ruby/2.6.0/gems/origen-0.57.2/origen_site_config.yml (local)
```
The issue then is that setting a ORIGEN_CENTRALIZED_SITE_CONFIG variable, origen assumes its going to find 2 site configs, and hardcodes its insertion into the configs array with an index of -3, which then fails out:
```
/.../ruby-2.6.0/lib/ruby/gems/2.6.0/gems/origen-0.55.3/lib/origen/site_config.rb:421:in `insert': index -3 too small for array; …
```

don't assume how many site configs are found in origen

---

lib/origen/pins/pin.rb
spec/pins_spec.rb
spec/pins_v3_spec.rb

The reason for this change is so we can put the pin type in the metadata automatically vs having to set it.  It is backwards compatible.

Updated pin type to be set automatically unless set by user

---

approved/nvm_concurrent_delays_with_sync.avc
approved/nvm_concurrent_delays_with_sync_part1.avc
environment/j750.rb
environment/v93k.rb
examples/pattern_generator.rb
lib/origen/generator/pattern_sequence.rb
pattern/concurrent_delays_with_sync.rb
target/origen_sim_dut.rb

This stops Origen crashing when calling tester.handshake for the V93K in a concurrent pattern scenario.
90% of the diff here is adding a new test case, the fix is just a simple bandaid added to `lib/origen/generator/pattern_sequence.rb`

Fixed tester.handshake crash for concurrent pats

---

lib/origen/site_config.rb

My previous PR introduced a bug, seems that it hits this code multiple times. My debugger statement was getting hit after some initializations were done, and Origen.top was in scope.
Seems during initial boot up (which in my testing was running a different Origen installation, which I can't modify based off how our company infrastructure is setup, making it difficult to test), it is not:
```
/usr/local/bundle/gems/origen-0.59.4/lib/origen/site_config.rb:421:in `block in configs!': undefined method `top' for Origen:Module (NoMethodError)
```

Origen.top isnt defined during bootup phase in SiteConfig class

---

Gemfile.lock
lib/origen/sub_blocks.rb

This fixes a bug that showed up in the CrossOrigen test cases.
It fixes that but unfortunately I've not been able to reproduce it in a test case within Origen core.
The intention of the changed line is to check if a const reference like `MY_CLASS` exists at the top-level namespace. However, under certain conditions (could be a Ruby 2.5 vs 2.6 thing for example) this coupled to the calling code such that something like `Placeholder::BLAH:BLAH::MY_CLASS` is what actually got checked.
The addition of the leading `::` enforces the original intent and all existing specs pass plus the specs in CrossOrigen now pass too.

Fix loader bug that manifested in CrossOrigen

---

config/commands.rb
lib/origen/loader.rb
lib/origen/model_initializer.rb
lib/origen/sub_blocks.rb
spec/sub_block_spec.rb
templates/web/guides/models/defining.md.erb

This is to support the direction we're heading in for supporting a chiplet based distributed architecture. 
The application structure consists of 3 layers: IP -> Chiplet -> Product
So say for example theres a PCIe App, an I/O App, and an app for Product A.
The PCIe app instantiates a pcie block and derivative: app/blocks/pcie/derivatives/pcie4
The I/O app instantiates an iod that uses pcie4: app/blocks/iod/derivatives/my_iod
```
sub_block :pcie, class_name: 'PcieApp::Pcie::Pcie4'
```
And then the product app instantiates an iod sub block:
```
sub_block :iod, class_name: 'IodApp::Iod::MyIod'
```
-----
Up to this point, if I understand the distributed architecture correctly, then nothing out of the norm at this point.
However, we need to be able to support product level and chiplet level …

support for remote block inheritance and overriding existing blocks

---

lib/origen/sub_blocks.rb
templates/web/guides/models/defining.md.erb

the requires that were helping make the constants sane starting getting troublesome when it tried to require say an attributes.rb file that called code that only worked after the blocks above it were set
Now only require files that should develop a namespace (ie model.rb/controller.rb by default), also allow for user to customize if they need to.
See the guides update for more detail

skip requiring non essential block files, updated docs for sub block override

---

lib/origen/loader.rb
spec/sub_block_spec.rb
templates/web/guides/models/defining.md.erb

When using the sub block inheritance feature, bugs and features can now propagate. This enables us along with the existing remote inheritance functionality to split bug/feature definitions into apps that are targeted towards modeling some IP, while apps that are targeted towards testing some aspect of an IP can focus on handling bugs/features in their flows when encountered.
```ruby
class MyIPBlock
include Origen::Model
feature :my_feature
end
class MySocBlock < MyIPBlock
include Origen::Model
end
class MyTop
include Origen::TopLevel
def initialize(options = {})
sub_block :my_block, class_name: 'MySocBlock', inherit: 'MyIPBlock'
end
end
dut.my_block.has_feature?(:my_feature)
=> true
```
The above works the same for bugs. You can disable bugs and/or feature inheritance by passing …

block inheritance feature can now propagate bugs and features

---

.github/workflows/regression_tests.yml
lib/origen/application/lsf.rb

Allow ability to modify the max job count before origen lsf handler sleeps to submit jobs
Edit: Update - Added ability to only check the current queue rather than all submitted jobs, as we have a service account that submits lots of jobs, and werent able to submit any origen jobs as there were a few thousand running in a different queue

Variable max lsf jobs

---

lib/origen/application/lsf.rb
origen_site_config.yml

didnt realize the remote job count method was called outside the class scope, fixed now, tested to be working

corrected scope access for config variables during remote job count

---

lib/origen/commands/lint.rb

when upreving to later origen, there are some lint rules that would be hard to get userbase to follow/would be a hassle for the existing codebase to move to. added option to specify a custom yml instead of the provided one

ability to for a custom rubocop config and support force autocorrect

---

config/rubocop/strict.yml

Applications generated by Origen with the new structure fail this rule and auto correct breaks applications. Probably best to just turn it off.

Enforcing this rule would lead to lots of rework

---

lib/origen/log.rb

If using multiple shells in the same workspace, there's chance logger files will step on each other, particularly `last`, and particularly noticeable with simulations. This will generate an exception, but doesn't affect a single pattern. However, this will kill a `flow` simulation prematurely if it occurs.
This is a quick fix to just catch any errors flushing to a log file and print them to the user, without propagating the exception.
For example, instead of seeing this:
You'll see:
Note the `warnings` here - just saying stale log file, which is expected, but now results in the warning instead of an exception.

Catch flush issues when a logger is closed

---

lib/origen/sub_blocks.rb

Original implementation was in place to protect against the valid scenario where a class_name was passed in but that file hadn't yet been loaded (e.g. the file would be loaded later during block materialization). If the class name truly didn't exist, it would error during materialization.
However, this unintentionally hid nested name errors. When the constantize method was called, it attempted to load that namespace. The namespace itself was correct, however its containing file was itself including a new module which did contain a namespace error. This was then squashed by the rescue, allowing the object to be created, and the file the user thought was getting included actually wasn't and didn't report the error either.
swapping to safe_constantize method essentially does the same as …

First call to constantize modifies the environment, hiding namespace errors on subsequent references to that class

---

lib/origen/sub_blocks.rb

I had a bug in my original override feature: the block that was being overwritten was never removed from the listeners. This occurs if you first remotely inherited a block that itself had a sub block, and then needed to override that inherited block's sub block.
Now we remove it from the listeners as we're replacing it with a new block, which will take its place in the listener list

sub block override bug was leaving old blocks in the list of listeners

---

lib/origen/callbacks.rb
lib/origen/loader.rb
lib/origen/model_initializer.rb
lib/origen/sub_blocks.rb
spec/sub_block_spec.rb

For remote inheritance there was a couple issues:
* remote blocks' sub blocks ended up getting double instantiated. This was at the time handled via override feature that would throw away the block and replace it later, but this was causing issues when the instantiation was editing data structures external to the block itself.
* Now when the remote block files are inherited, it first delays handling the remote sub_blocks.rb file until after the current block is fully booted. Then, when parsing the remote sub_blocks.rb, any sub_block that already exists for the current block is skipped.
* bugs and features weren't correctly propagating with lazy loading if those bugs/features were sourced from the remote blocks ancestors
* remote inheritance now sources the remote blocks ancestry chain to …

Remote block inheritance improvement and lazy block double on_create fix
